graph TD
    0["Servidor 1"]
    1["Switch 1"]
    2["Computador 1"]
    3["Access Point 1"]
    4["Computador 2"]
    5["Servidor 2"]
    6["Switch 2"]
    7["Computador 3"]
    8["Access Point 2"]
    9["Computador 4"]
    10["Servidor 3"]
    11["Computador 5"]
    12["Computador 6"]
    13["Computador 7"]
    0 -- Fibra --> 1
    1 -- Cabo --> 11
    1 -- Satélite --> 5
    1 -- Cabo --> 3
    1 -- WiFi --> 2
    3 -- Cabo --> 13
    3 -- WiFi --> 4
    5 -- Fibra --> 6
    6 -- Satélite --> 10
    6 -- WiFi --> 8
    6 -- Cabo --> 7
    8 -- WiFi --> 9
    11 -- WiFi --> 12
